name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build
    outputs:
      file: ${{ steps.filename.outputs.file }}
      buildname: ${{ steps.filename.outputs.buildname }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"
      - name: print
        run: |
          pip install nuitka zstandard orderedset
          python -m nuitka --version
