name: Release

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Test File
        run: |
          touch
          nuitka --standalone --show-progress --output-dir=build --user-package-configuration-file=nuitka.yml .\main.py

      - name: Get Name
        id: filename
        run: |
          echo 1${{ matrix.os }} > 1${{ matrix.os }}
          echo 2${{ matrix.os }} > 2${{ matrix.os }}

      - name: Upload 
        
