name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build
    outputs:
      file: ${{ steps.filename.outputs.file }}
      buildname: ${{ steps.filename.outputs.buildname }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare environment
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"
      - name: print
        run: |
          pip install nuitka zstandard orderedset
          python -m nuitka --onefile --standalone --output-dir=nuitka main.py
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test
          files: nuitka/main.bin
