name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build
    outputs:
      file: ${{ steps.filename.outputs.file }}
      buildname: ${{ steps.filename.outputs.buildname }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get Name
        id: filename
        run: |
          echo 1${{ matrix.os }} > 1${{ matrix.os }}
          echo 2${{ matrix.os }} > 2${{ matrix.os }}

      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            1${{ matrix.os }}
            2${{ matrix.os }}
            
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "*"
